Import

In [58]:
import pandas as pd
df = pd.read_csv(
'https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb'
)

C:\Users\ivann\AppData\Local\Temp\ipykernel_19708\3566284707.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [ ]:
df.head()

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,1,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,2,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01,Ain,4,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01,Ain,5,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01,Ain,6,Ambléon,Nathalie,ARTHAUD,0

QUESTION 1

In [62]:
# code_commune

print(type(df["code_departement"][1]))
print(type(df["code_commune"][1]))

communes = df

communes["code_commune"] = communes["code_commune"].astype(str)
communes["code_commune"] = ("000" + communes["code_commune"]).str[-3:]
communes["code_commune"] = communes["code_departement"] + communes["code_commune"]


# candidat

communes["candidat"] = communes["prenom"] + " " + communes["nom"]

communes.head()

<class 'str'>
<class 'str'>

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix,candidat
0,01,Ain,01001,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3,Nathalie ARTHAUD
1,01,Ain,01002,L'Abergement-de-Varey,Nathalie,ARTHAUD,2,Nathalie ARTHAUD
2,01,Ain,01004,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38,Nathalie ARTHAUD
3,01,Ain,01005,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8,Nathalie ARTHAUD
4,01,Ain,01006,Ambléon,Nathalie,ARTHAUD,0,Nathalie ARTHAUD

QUESTION 2

In [125]:
candidats = communes["candidat"].nunique()
f"En 2022, il y avait {candidats} candidats à l'élection présidentielle."

"En 2022, il y avait 12 candidats à l'élection présidentielle."

QUESTION 3

In [98]:
voix_candidats = communes.groupby("candidat")["voix"].sum().reset_index(name = "Nombre votes")
voix_candidats = voix_candidats.sort_values(by = "Nombre votes", ascending = False)

total_voix = voix_candidats["Nombre votes"].sum()
voix_candidats["Score"] = (voix_candidats["Nombre votes"] / total_voix) * 100
voix_candidats["Score"] = voix_candidats["Score"].round(2).astype(str) + "%"

voix_candidats

                 candidat  Nombre votes   Score
1         Emmanuel MACRON       9783058  27.85%
5           Marine LE PEN       8133828  23.15%
4      Jean-Luc MÉLENCHON       7712520  21.95%
11           Éric ZEMMOUR       2485226   7.07%
9        Valérie PÉCRESSE       1679001   4.78%
10          Yannick JADOT       1627853   4.63%
3           Jean LASSALLE       1101387   3.13%
2          Fabien ROUSSEL        802422   2.28%
7   Nicolas DUPONT-AIGNAN        725176   2.06%
0            Anne HIDALGO        616478   1.75%
8         Philippe POUTOU        268904   0.77%
6        Nathalie ARTHAUD        197094   0.56%

QUESTION 4

In [122]:
score_departement = communes.groupby(["code_departement", "candidat"])["voix"].sum().reset_index(name = "Nombre votes")
score_departement["votes_total"] = score_departement.groupby("code_departement")["Nombre votes"].transform("sum")
score_departement = score_departement.sort_values(by = ["code_departement", "Nombre votes"], ascending = [True, False])
score_departement["Score"] = (score_departement["Nombre votes"] / score_departement["votes_total"]) * 100
score_departement["Score"] = score_departement["Score"].round(2).astype(str) + "%"

In [100]:
# Vérification
score_departement.head()

   code_departement            candidat  Nombre votes  votes_total   Score
1                01     Emmanuel MACRON         92206       333024  27.69%
5                01       Marine LE PEN         86755       333024  26.05%
4                01  Jean-Luc MÉLENCHON         57832       333024  17.37%
11               01        Éric ZEMMOUR         27530       333024   8.27%
9                01    Valérie PÉCRESSE         17572       333024   5.28%

QUESTION 5

In [123]:
score_departement = score_departement.merge(voix_candidats, on="candidat", how="left")
score_departement.rename(columns={"Nombre votes_x": "Votes_département",
                                  "Nombre votes_y": "Votes_National",
                                  "Score_x": "Score_département",
                                  "Score_y": "Score_National"}, inplace=True)

score_departement = score_departement.drop(columns=["votes_total"])

score_departement[score_departement["code_departement"] == "11"]

,code_departement,candidat,Votes_département,Score_département,Votes_National,Score_National
120,11,Marine LE PEN,64027,30.14%,8133828,23.15%
121,11,Emmanuel MACRON,43104,20.29%,9783058,27.85%
122,11,Jean-Luc MÉLENCHON,42039,19.79%,7712520,21.95%
123,11,Éric ZEMMOUR,18434,8.68%,2485226,7.07%
124,11,Jean LASSALLE,12382,5.83%,1101387,3.13%
125,11,Valérie PÉCRESSE,7350,3.46%,1679001,4.78%
126,11,Yannick JADOT,6322,2.98%,1627853,4.63%
127,11,Anne HIDALGO,6166,2.9%,616478,1.75%
128,11,Fabien ROUSSEL,5622,2.65%,802422,2.28%
129,11,Nicolas DUPONT-AIGNAN,4206,1.98%,725176,2.06%
130,11,Philippe POUTOU,1748,0.82%,268904,0.77%
131,11,Nathalie ARTHAUD,1026,0.48%,197094,0.56%

QUESTION 6

QUESTION 7

QUESTION 8