Import

In [ ]:
import pandas as pd
df = pd.read_csv(
'https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb'
)

KeyboardInterrupt:

In [8]:
df.head()

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,1,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,2,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01,Ain,4,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01,Ain,5,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01,Ain,6,Ambléon,Nathalie,ARTHAUD,0

QUESTION 1

In [30]:
# code_commune

print(type(df["code_departement"][1]))
print(type(df["code_commune"][1]))

df["code_commune"] = df["code_commune"].astype(str)
df["code_commune"] = df["code_departement"] + df["code_commune"]


# candidat

df["candidat"] = df["prenom"] + " " + df["nom"]

df.head()

<class 'str'>
<class 'str'>

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix,candidat
0,01,Ain,010101011,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3,Nathalie ARTHAUD
1,01,Ain,010101012,L'Abergement-de-Varey,Nathalie,ARTHAUD,2,Nathalie ARTHAUD
2,01,Ain,010101014,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38,Nathalie ARTHAUD
3,01,Ain,010101015,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8,Nathalie ARTHAUD
4,01,Ain,010101016,Ambléon,Nathalie,ARTHAUD,0,Nathalie ARTHAUD

QUESTION 2

QUESTION 3

In [ ]:
voix_candidats = df.groupby("candidat")["voix"].sum().reset_index(name = "Nombre votes")
voix_candidats = voix_candidats.sort_values(by = "Nombre votes", ascending = False)

total_voix = voix_candidats["Nombre votes"].sum()
voix_candidats["Score"] = (voix_candidats["Nombre votes"] / total_voix) * 100
voix_candidats["Score"] = voix_candidats["Score"].round(2).astype(str) + "%"

voix_candidats

                 candidat  Nombre votes   Score
1         Emmanuel MACRON       9783058  27.85%
5           Marine LE PEN       8133828  23.15%
4      Jean-Luc MÉLENCHON       7712520  21.95%
11           Éric ZEMMOUR       2485226   7.07%
9        Valérie PÉCRESSE       1679001   4.78%
10          Yannick JADOT       1627853   4.63%
3           Jean LASSALLE       1101387   3.13%
2          Fabien ROUSSEL        802422   2.28%
7   Nicolas DUPONT-AIGNAN        725176   2.06%
0            Anne HIDALGO        616478   1.75%
8         Philippe POUTOU        268904   0.77%
6        Nathalie ARTHAUD        197094   0.56%

QUESTION 4